### ISSUE TITLE
Invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by jorisvh** [balinterdi/i15r#38]
Hello,

Launching i15r (with the dry run option), I got the following error:

/Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r/pattern_matcher.rb:44:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r/pattern_matcher.rb:44:in `run'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r.rb:84:in `sub_plain_strings'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r.rb:77:in `internationalize_file'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r.rb:94:in `block in internationalize!'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r.rb:94:in `each'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/lib/i15r.rb:94:in `internationalize!'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/gems/i15r-0.5.3/bin/i15r:53:in `<top (required)>'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/bin/i15r:23:in `load'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/bin/i15r:23:in `<main>'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
        from /Users/jorisvh/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'

The issue was that I left a comment in French in my code (with the é letter), so it was not even due to some hardcoded string to replace. It could be really great to use i15r with full UTF-8 support.

Thank you and keep up the good work !

Joris

**Comment by SimplySuggest** [comment]
This can fix it https://github.com/balinterdi/i15r/pull/40

**Comment by balinterdi** [comment]
Fixed by #40

**Comment by balinterdi** [comment]
Released version 0.5.5 that fixes the above issue.
